
colocation_homepage:
    path:     /user/colocation
    defaults: { _controller: ColocationBundle:Default:index }

back:
    path:     /user/colocation/ajout
    defaults: { _controller: ColocationBundle:Default:ajout}

supprimer:
      path:     /user/colocation/supprimer/{id}
      defaults: { _controller: ColocationBundle:Default:supprimer }

annonces:
      path:     /user/colocation/MesAnnonce
      defaults: { _controller: ColocationBundle:Default:supprimera }

recherche:
      path:     /user/colocation/recherche
      defaults: { _controller: ColocationBundle:Default:recherche }

show_specific_colocation:
      path:     /user/colocation/show/{id}
      defaults: { _controller: ColocationBundle:Default:show }

mesoffres:
      path:     /user/colocation/mesoffres
      defaults: { _controller: ColocationBundle:Default:mesoffres}

reponse_offre:
      path:     /user/colocation/reponse/{id}
      defaults: { _controller: MyAppMailBundle:Default:reponse}

indexColocation:
      path:     /user/colocation/indexColocation
      defaults: { _controller: ColocationBundle:Default:indexColocation}
mail:
      path:     /mail
      defaults: { _controller: ColocationBundle:Default:mail}
modifier:
      path:   /modifier/{id}
      defaults: { _controller: ColocationBundle:Default:modifier}

affichoffrecoloc:
      path:   /affichoffrecoloc
      defaults: { _controller: ColocationBundle:Default:affichoffrecoloc}

affichdemanderecoloc:
      path:   /affichdemandecoloc
      defaults: { _controller: ColocationBundle:Default:affichdemandecoloc}












