colocation_homepage:
    path:     /user/colocation
    defaults: { _controller: ColocationBundle:Default:index }

back:
    path:     /user/colocation/ajout
    defaults: { _controller: ColocationBundle:Default:ajout}

supprimer:
      path:     /user/colocation/supprimer/{id}
      defaults: { _controller: ColocationBundle:Default:supprimer }

annonces:
      path:     /user/colocation/MesAnnonce
      defaults: { _controller: ColocationBundle:Default:supprimer }






