objet_api_homepage:
    path:     /
    defaults: { _controller: ObjetAPIBundle:Default:index }

objtrouv:
    path:     /objtrouv
    defaults: { _controller: ObjetAPIBundle:Default:getObjTrouv }

objperd:
    path:     /objperd
    defaults: { _controller: ObjetAPIBundle:Default:getObjPerd }

reclamer:
    path:     /reclamer/{id}/{iduser}
    defaults: { _controller: ObjetAPIBundle:Default:reclamerObj }

supprimer_reclamation:
    path:     /suppprec/{id}
    defaults: { _controller: ObjetAPIBundle:Default:supprimerInteraction }


