co_voiturage_api_all:
    path:     /offres
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturage }

co_voiturage_api_delete:
    path:     /offres/delete
    defaults: { _controller: CoVoiturageAPISBundle:Default:deleteCoVoiturage }

co_voiturage_api_ago:
    path:     /offres/ago
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageAgo }

co_voiturage_api_date:
    path:     /offres/date
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageDateString }

co_voiturage_requests_api_all:
    path:     /requests
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageRequests }

co_voiturage_requests_api_add:
    path:     /requests/add
    defaults: { _controller: CoVoiturageAPISBundle:Default:addRequest }

co_voiturage_own_requests_api_all:
    path:     /requests/own
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageOwnRequests }

co_voiturage_requests_api_ago:
    path:     /requests/ago
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageRequestsAgo }

co_voiturage_days_api_all:
    path:     /days
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageDays }

co_voiturage_maps:
    path:     /map
    defaults: { _controller: CoVoiturageAPISBundle:Default:getCoVoiturageMaps }

