<?php

namespace CoVoiturageBundle\Repository;

/**
 * CoVoiturageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoVoiturageRepository extends \Doctrine\ORM\EntityRepository
{
}
