<?php

namespace CoVoiturageBundle\Repository;

/**
 * CoVoiturageRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoVoiturageRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
