<?php

namespace CoVoiturageBundle\Repository;

/**
 * CoVoiturageRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoVoiturageRequestsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderedBy()
    {
        $q = $this->getEntityManager()->createQuery("SELECT p
              FROM CoVoiturageBundle:CoVoiturageRequests p
              ORDER BY p.etat DESC , p.created DESC");
        return $q->getResult();
    }
}
