<?php

namespace CoVoiturageBundle\Repository;

/**
 * CoVoiturageDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoVoiturageDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
