<?php

namespace ObjetBundle\Repository;

/**
 * InteractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionRepository extends \Doctrine\ORM\EntityRepository
{
}
