<?php

namespace ObjetBundle\Repository;

/**
 * InteractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findtrouver($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT i from ObjetBundle:Interaction i WHERE i.idObjet=:id")
            ->setParameter('id',$id);
        return $q->getResult();

    }
}
