<?php

namespace ObjetBundle\Repository;

/**
 * ObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function objperd(){
        $q = $this->getEntityManager()
            ->createQuery("select o from ObjetBundle:Objet o WHERE o.nature='Objet Perdu'");
        return $q->getResult();

    }
   public function objtrouv(){
        $q = $this->getEntityManager()
            ->createQuery("select o from ObjetBundle:Objet o WHERE o.nature='Objet Trouvé'");
        return $q->getResult();
    }












}
