<?php

namespace ObjetBundle\Repository;

/**
 * SignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findtrouver($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT i from ObjetBundle:Signal s WHERE s.idObjet=:id")
            ->setParameter('id',$id);
        return $q->getResult();

    }


}
