<?php

namespace ObjetBundle\Repository;

/**
 * traitafterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traitafterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findtrouver($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT s from ObjetBundle:traitafter s WHERE s.interaction=:id")
            ->setParameter('id',$id);
        return $q->getResult();

    }
}
