e_index:
    path:     /
    defaults: { _controller: "EventBundle:Event:index" }
    methods:  GET

e_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:Event:show" }
    methods:  GET

e_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }
    methods:  [GET, POST]

e_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }
    methods:  [GET, POST]

e_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    methods:  DELETE
