espace_etude_homepage:
    path:     /
    defaults: { _controller: EspaceEtudeBundle:Default:index }
recherche_document:
    path:     /rechercheDocument
    defaults: { _controller: EspaceEtudeBundle:Document:recherche }

afficher_matiere:
    path:     /afficherMatiere/{section}
    defaults: { _controller: EspaceEtudeBundle:Matieres:afficherMatiere }

afficher_documents:
    path:     /afficherDocuments/{id}
    defaults: { _controller: EspaceEtudeBundle:Document:afficherDocuments }

supp_documents:
    path:     /supprimerdoc/{idDoc}/{idMatiere}
    defaults: { _controller: EspaceEtudeBundle:Document:supprimerDocument }
modif_documents:
    path:     /modif/{idDoc}/{idMatiere}
    defaults: { _controller: EspaceEtudeBundle:Document:modifierDocument }
valider_documents:
    path:     /valid/{idDoc}/{idMatiere}
    defaults: { _controller: EspaceEtudeBundle:Document:validerDocument }
afficher_section:
    path:     /sections/{niveau}
    defaults: { _controller: EspaceEtudeBundle:Matieres:afficherSection }
update_notif:
    path:     /update
    defaults: { _controller: EspaceEtudeBundle:Default:updateNotif }






espace_etude_homepdsqge:
    path:     /test
    defaults: { _controller: EspaceEtudeBundle:Default:test }
