objet_homepage:
    path:     /objets
    defaults: { _controller: ObjetBundle:Objet:Objet }

objperd_homepage:
    path:     /objets/objperd
    defaults: { _controller: ObjetBundle:Objet:coinobjperd }

objtrouv_homepage:
    path:     /objets/objtrouv
    defaults: { _controller: ObjetBundle:Objet:coinobjtrouv }

ajoutobjtrouv:
    path:     /objets/objetstrouves/ajoutobjtrouv
    defaults: { _controller: ObjetBundle:Objet:ajoutobjtrouv }


ajoutobjperdtrouv:
    path:     /objets/objetsperdus/ajoutobjperd
    defaults: { _controller: ObjetBundle:Objet:ajoutobjperd }



affichobjperd:
    path:     /objets/objetsperdus/affichobj
    defaults: { _controller: ObjetBundle:Objet:affichobjperd }

affichobjtrouv:
    path:     /objets/objetstrouves/affichobj
    defaults: { _controller: ObjetBundle:Objet:affichobjtrouv }

deleteobj:
    path:     /objets/deleteobj/{id}
    defaults: { _controller: ObjetBundle:Objet:deleteobj }

updateobj:
    path:     /objets/updateobj/{id}
    defaults: { _controller: ObjetBundle:Objet:updateobj }
