forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

espace_etude:
    resource: "@EspaceEtudeBundle/Resources/config/routing.yml"
    prefix:   /etude

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

objet:
    resource: "@ObjetBundle/Resources/config/routing.yml"
    prefix:   /objet

co_voiturage:
    resource: "@CoVoiturageBundle/Resources/config/routing.yml"
    prefix:   /covoiturage

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


colocation:
    resource: "@ColocationBundle/Resources/config/routing.yml"
    prefix:   /

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /