<?php

namespace ColocationBundle\Repository;

/**
 * ColocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColocationRepository extends \Doctrine\ORM\EntityRepository
{
   public function recherche($valeur)
    {
        $query = ColocationRepository::createQueryBuilder('r')
            ->where('UPPER(r.ville) LIKE UPPER(:valeur)')
            ->setParameter('valeur', '%'.$valeur.'%')
            ->getQuery();
        return $query->getResult();
    }

    public function demcoloc(){
        $q=$this->getEntityManager()
            ->createQuery("select (c) from ColocationBundle:Colocation c WHERE c.nature ='Demande' ");
        return $q->getResult();

    }

    public function offcoloc(){
        $q=$this->getEntityManager()
            ->createQuery("select (c) from ColocationBundle:Colocation c WHERE c.nature ='Offre' ");
            return $q->getResult();

    }

}
