<?php

namespace UserBundle\Repository;

/**
 * UserphotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserphotoRepository extends \Doctrine\ORM\EntityRepository
{
}
