user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_news:
    path:     /home
    defaults: { _controller: UserBundle:Default:news }

admin:
    path:     /admin
    defaults: { _controller: UserBundle:Default:admin }

admincovoffres:
    path:     /admin/offres
    defaults: { _controller: UserBundle:Default:CoVoiturageOffre }

admincovdemande:
    path:     /admin/demandes
    defaults: { _controller: UserBundle:Default:CoVoiturageDemande }

admincovoffresparam:
    path:     /admin/offres/p
    defaults: { _controller: UserBundle:Default:CoVoiturageViewOffreParam }

admincovdemandesparam:
    path:     /admin/demandes/p
    defaults: { _controller: UserBundle:Default:CoVoiturageViewDemandeParam }

admincovoffredelete:
    path:     /admin/offres/delete
    defaults: { _controller: UserBundle:Default:CoVoiturageDeleteOffre }

admincovdemandedelete:
    path:     /admin/demandes/delete
    defaults: { _controller: UserBundle:Default:CoVoiturageDeleteDemande }

admincovoffrerequestdelete:
    path:     /admin/offres/deleterequest
    defaults: { _controller: UserBundle:Default:CoVoiturageDeleteOffreRequest }

admincovdemanderequestdelete:
    path:     /admin/demandes/deleterequest
    defaults: { _controller: UserBundle:Default:CoVoiturageDeleteDemandeRequest }

admininfooffres:
    path:     /admin/offres/info
    defaults: { _controller: UserBundle:Default:CoVoiturageInfoOffre }

admininfodemande:
    path:     /admin/demandes/info
    defaults: { _controller: UserBundle:Default:CoVoiturageInfoDemande }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

afficher_section_admin:
    path:     /admin/section
    defaults: { _controller: UserBundle:Default:section }
delete_section:
    path:     /admin/section/{id}
    defaults: { _controller: UserBundle:Default:delete }

affiche:
    path:     /admin/colocation
    defaults: { _controller: UserBundle:Default:colocation }
supprimer:
      path:     /user/colocation/supprimer/{id}
      defaults: { _controller: UserBundle:Default:supprimer }

afficher_matiere_admin:
    path:     /admin/matiere/{id}
    defaults: { _controller: UserBundle:Default:matiere }
delete_matiere:
    path:     /admin/matiere/{id}/{ids}
    defaults: { _controller: UserBundle:Default:deleteMatiere }
update_matiere:
    path: /admin/update
    defaults: {_controller: UserBundle:Default:updateMatiere}
update_section:
    path: /admin/sectionupdate
    defaults: {_controller: UserBundle:Default:updateSection}


admin_index:
    path:     /adminIndex
    defaults: { _controller: "UserBundle:Default:indexAdmin" }
    methods:  GET

admin_show:
    path:     /{id}/adminShow
    defaults: { _controller: "UserBundle:Default:showAdmin" }
    methods:  GET

admin_approuver:
    path:     /{id}/adminApprouver
    defaults: { _controller: "UserBundle:Default:approuver" }
    methods:  GET

admin_index_approuve:
    path:     /adminIndexApprouver
    defaults: { _controller: "UserBundle:Default:indexAdminApprouver" }
    methods:  GET

admin_objet_non_approuve:
    path:     /adminaffichobjnonApprouver
    defaults: { _controller: "UserBundle:Default:indexAdminObjet" }
    methods:  GET

admin_fct_OBJET_approuver:
    path:     /{id}/adminObjetApprouver
    defaults: { _controller: "UserBundle:Default:approuverObjetAction" }
    methods:  GET

admin_objet_approuve:
    path:     /adminaffichobjApprouver
    defaults: { _controller: "UserBundle:Default:indexAdminObjetApprouver" }
    methods:  GET



