co_voiturage_homepage:
    path:     /
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:read }

co_voiturage_addoffreview:
    path:     /offre/add
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:addOffreView }

co_voiturage_adddemandeview:
    path:     /demande/add
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:addDemandeView }

co_voiturage_modifyoffreview:
    path:     /offre/modify
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:modifyOffreView }

co_voiturage_modifydemandeview:
    path:     /demande/modify
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:modifyDemandeView }

co_voiturage_addoffre:
    path:     /offres/adding
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:addOffre }

co_voiturage_adddemande:
    path:     /demande/adding
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:addDemande }

co_voiturage_deleteoffre:
    path:     /offres/deleting
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:deleteOffre }

co_voiturage_deletedemande:
    path:     /demande/deleting
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:deleteDemande }

co_voiturage_modifyoffre:
    path:     /offres/modifying
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:modifyOffre }

co_voiturage_modifydemande:
    path:     /demande/modifying
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:modifyDemande }


co_voiturage_viewoffre:
    path:     /offres
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOffre }

co_voiturage_viewdemande:
    path:     /demande
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewDemande }

co_voiturage_viewownoffre:
    path:     /offres/own
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOwnOffre }

co_voiturage_viewowndemande:
    path:     /demande/own
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOwnDemande }

co_voiturage_viewownoffreparam:
    path:     /offres/own/param
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOwnOffreParam }

co_voiturage_viewowndemandeparam:
    path:     /demande/own/param
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOwnDemandeParam }

co_voiturage_viewoffreparam:
    path:     /offres/param
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewOffreParam }

co_voiturage_viewdemandeparam:
    path:     /demande/param
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:viewDemandeParam }

co_voiturage_requestoffre:
    path:     /offres/request
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:requestOffre }

co_voiturage_requestdemande:
    path:     /demande/request
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:requestDemande }

co_voiturage_infooffre:
    path:     /offres/info
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:infoOffre }

co_voiturage_infodemande:
    path:     /demande/info
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:infoDemande }

co_voiturage_acceptoffrerequest:
    path:     /offres/accept
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:acceptOffreRequest }

co_voiturage_acceptdemanderequest:
    path:     /demande/accept
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:acceptDemandeRequest }

co_voiturage_refuseoffrerequest:
    path:     /offres/refuse
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:refuseOffreRequest }

co_voiturage_refusedemanderequest:
    path:     /demande/refuse
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:refuseDemandeRequest }

co_voiturage_deleteoffrerequest:
    path:     /offres/delete
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:deleteOffreRequest }

co_voiturage_deletedemanderequest:
    path:     /demande/delete
    defaults: { _controller: CoVoiturageBundle:CoVoiturage:deleteDemandeRequest }
