<?php

namespace EspaceEtudeBundle\Repository;

/**
 * notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->andWhere('a.vu=0')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
